name: API Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 00 4 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: API Tests
      run: mvn clean test -Dsuite=suite
      
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Logs
        path: logs/

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit

    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: ./test-output/reports/



